# Jeedom Info

jeedom_ip: "1.1.1.1"
jeedom_api_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# Host Info (Remote host DB)

host_infos:
  dev:
    address: "127.0.0.1"
    local: True
  prod:
    address: "2.2.2.2"
    local: False

# Flower Info (Mi-Flora)

flower_infos:
  L_Flower:
    mac: "C0:00:00:00:00:01"
    active: True
  R_Flower:
    mac: "C0:00:00:00:00:01"
    active: True

# DB Info (Postgres)

db_infos:
  dbname: "my_db" 
  user: "my_user" 
  password: "my_password" 
  port: 5432
